export const routes = {
    home: '/',
    login: '/login',
    register: '/register',
    profile: '/profile',
    notFound: '/404',
    unauthorized: '/401',
    product: '/product',
    promotions: '/promotions',
    promotionDetail: '/promotions/:id',
    aboutUs: '/about-us',
    contact: '/contact',
    cart: '/cart',
    placeOrder: '/place-order',
    productDetail: '/product/:id',
    manageProduct: '/manage-product',
    restricted: '/restricted',
    manageOrders: '/manage-orders',
    checkout: '/checkout',
    historyOrder: '/history-order',
};
